services:
  postgres:
    image: postgres:16
    container_name: expenses-postgres
    environment:
      POSTGRES_DB: expenses
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - expenses_pgdata:/var/lib/postgresql/data

volumes:
  expenses_pgdata: